# Generated by Django 6.0.3 on 2026-03-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0002_crawlrawdata_record_type_crawlrawdata_unique_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlrawdata',
            name='item_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='crawlrawdata',
            name='source_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='crawltarget',
            name='title',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='crawltarget',
            name='url',
            field=models.URLField(max_length=2000, unique=True),
        ),
    ]
