# Generated by Django 6.0.3 on 2026-03-31 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('reviews', '0002_alter_review_options_alter_reviewai_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSimilarityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='upskyy/e5-small-korean', max_length=100)),
                ('similarity_score', models.FloatField()),
                ('similarity_label', models.CharField(max_length=30)),
                ('similarity_threshold', models.FloatField(default=0.45)),
                ('source_review_snapshot', models.TextField()),
                ('compared_review_snapshot', models.TextField()),
                ('compared_username_snapshot', models.CharField(blank=True, max_length=150)),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compared_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compared_similarity_results', to='reviews.review')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_similarity_results', to='products.product')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_similarity_results', to=settings.AUTH_USER_MODEL)),
                ('source_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_similarity_results', to='reviews.review')),
            ],
            options={
                'ordering': ['-similarity_score', '-analyzed_at'],
                'constraints': [models.UniqueConstraint(fields=('source_review', 'compared_review', 'model_name'), name='unique_review_similarity_result')],
            },
        ),
    ]
