# Generated by Django 6.0.3 on 2026-04-01 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_gateway', '0001_initial'),
        ('products', '0001_initial'),
        ('reviews', '0002_alter_review_options_alter_reviewai_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('PENDING', '대기중'), ('STARTED', '진행중'), ('SUCCESS', '완료'), ('FAILURE', '실패')], default='PENDING', max_length=20)),
                ('model_name', models.CharField(default='upskyy/e5-small-korean', max_length=100)),
                ('similarity_threshold', models.FloatField(default=0.45)),
                ('candidate_count', models.PositiveIntegerField(default=0)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='reviewsimilarityresult',
            options={'ordering': ['-analyzed_at']},
        ),
        migrations.RemoveConstraint(
            model_name='reviewsimilarityresult',
            name='unique_review_similarity_result',
        ),
        migrations.AlterField(
            model_name='reviewsimilarityresult',
            name='analyzed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reviewsimilarityresult',
            name='compared_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_results_as_compared', to='reviews.review'),
        ),
        migrations.AlterField(
            model_name='reviewsimilarityresult',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_results', to='products.product'),
        ),
        migrations.AlterField(
            model_name='reviewsimilarityresult',
            name='similarity_label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reviewsimilarityresult',
            name='source_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_results_as_source', to='reviews.review'),
        ),
        migrations.AddField(
            model_name='aianalysistask',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_analysis_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aianalysistask',
            name='source_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis_tasks', to='reviews.review'),
        ),
        migrations.RemoveField(
            model_name='reviewsimilarityresult',
            name='compared_review_snapshot',
        ),
        migrations.RemoveField(
            model_name='reviewsimilarityresult',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reviewsimilarityresult',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='reviewsimilarityresult',
            name='similarity_threshold',
        ),
        migrations.RemoveField(
            model_name='reviewsimilarityresult',
            name='source_review_snapshot',
        ),
    ]
